
TYPE
	DoorStates : 	STRUCT 
		ST_INIT : UINT;
		ST_UNKNOWN : UINT;
		ST_OPEN : UINT;
		ST_CLOSE : UINT;
		ST_ACC_POS : UINT;
		ST_ACC_NEG : UINT;
		ST_POS : UINT;
		ST_NEG : UINT;
		ST_DEC_POS : UINT;
		ST_DEC_NEG : UINT;
	END_STRUCT;
END_TYPE
